import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { BrowserRouter as Router, Routes, Route } from 'react-router-dom';
import UploadPage from '@features/Upload/UploadPage';
import AssignmentNamePage from '@features/Assignment/AssignmentNamePage';
import AssignmentWeekPage from '@features/Assignment/AssignmentWeekPage';
import SimilarityLoadingPage from '@features/Similarity/SimilarityLoadingPage';
import SimilarityCompletePage from '@features/Similarity/SimilarityCompletePage';
import ResultPage from '@features/Result/ResultPage';
import './index.css';
import 'react-tooltip/dist/react-tooltip.css';
import ComparePage from '@features/Compare/\bComparePage';
import PlagiarismDecisionPage from '@features/Result/PlagiarismDecisionPage';
import ResultSaveCompletePage from '@features/Result/ResultSaveCompletePage';
import DashboardPage from '@features/Dashboard/DashboardPage';
import LoginPage from '@features/Account/LoginPage';
import HomePage from '@features/Home/HomePage';
import SignupPage from '@features/Account/SignupPage';
const App = () => {
    return (_jsx(Router, { children: _jsxs(Routes, { children: [_jsx(Route, { path: "/", element: _jsx(HomePage, {}) }), _jsx(Route, { path: "/assignment/name", element: _jsx(AssignmentNamePage, {}) }), _jsx(Route, { path: "/assignment/week", element: _jsx(AssignmentWeekPage, {}) }), _jsx(Route, { path: "/upload", element: _jsx(UploadPage, {}) }), _jsx(Route, { path: "/analysis/loading", element: _jsx(SimilarityLoadingPage, {}) }), _jsx(Route, { path: "/analysis/complete", element: _jsx(SimilarityCompletePage, {}) }), _jsx(Route, { path: "/result", element: _jsx(ResultPage, {}) }), _jsx(Route, { path: "/result/save", element: _jsx(ResultSaveCompletePage, {}) }), _jsx(Route, { path: "/compare/:from/:to", element: _jsx(ComparePage, {}) }), _jsx(Route, { path: "/decision", element: _jsx(PlagiarismDecisionPage, {}) }), _jsx(Route, { path: "/dashboard", element: _jsx(DashboardPage, {}) }), _jsx(Route, { path: "/login", element: _jsx(LoginPage, {}) }), _jsx(Route, { path: "/signup", element: _jsx(SignupPage, {}) })] }) }));
};
export default App;
